<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.3.11.1 setup script
 * Date: Mon, 16 Mar 2015 18:02:05 +0100
 */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['MaxRows'] = 1000;
?>